name:         Text-TabFile
version:      1.04
version_from: lib/Tkx/Login.pm
installdirs:  site
requires:
    Tkx:               1.00

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
