---
abstract: 'A Tkx based Login screen'
author:
  - 'Phil Pollard <bennie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.92, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tkx-Login
no_index:
  directory:
    - t
    - inc
    - t
provides:
  Tkx::Login:
    file: lib/Tkx/Login.pm
    version: 1.09
requires:
  Test::More: 0
  Tkx: 0
  perl: 5.006001
resources:
  bugtracker: https://rt.cpan.org/Dist/Display.html?Name=Tkx-Login
  repository: git://github.com/bennie/perl-Tkx-Login.git
version: 1.09
